# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82cf502c898658a05a4f871c3c738a1e05e0edb089043349909e903a7cb256b5143803b50a08d894ae97848bdd3c194f67b4c583b0f21e0de443548c7e2d7ff2

test:
  secret_key_base: 8a87cdbcb7a20c6b1af414b340ca5c07d5425573c77ad32dde80eccc69ea4ebdda09ca4764aca14c149286a4b5e7485085f7f9057bc54fbbca46bc127538bed3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
